{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pvc
  labels:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
status: {}
{{- end }}
