{{- if not .Values.config.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-creds
data:
  username: {{ .Values.config.database.username | b64enc | quote }}
  password: {{ .Values.config.database.password | default (randAlphaNum 30) | b64enc | quote }}
{{- end }}
---
{{- if not .Values.config.mail.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp-creds
data:
  username: {{ .Values.config.mail.username | b64enc | quote }}
  password: {{ .Values.config.mail.password | default (randAlphaNum 30) | b64enc | quote }}
{{- end }}