{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sentry.serviceAccountName" . }}
  labels:
{{ include "sentry.labels" . | indent 4 }}
  annotations:
  {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{ end }}